[package]
name = "winner_snipe"
version = "0.1.0"
edition = "2021"

[dependencies]
artemis-core = { path = "../../artemis-core" }
ethers = { workspace = true }
async-trait = "0.1"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
hex = "0.4"